### PR TITLE
fix(sync): wait until persistence adapters ready before first sync

### LINKED ISSUE #943: `SyncManager` fails to find the `lastFinishedSync` when using an async persistence adapter
The `SyncManager` fails to find the `lastFinishedSync` when using an async persistence adapter when attempting to start sync soon after creation. This issue only happens with async persistence adapters that might take several ms loading data like an [`indexeddb persister`](https://github.com/obedm503/trellix-offline/blob/8dbe7d46e2774ded0bfbf3a75fdaa9bf9d2a32d7/signaldb/src/idb-persister.ts) and not with sync persisters like local storage.

```ts
const syncManager = new SyncManager({  
  persistenceAdapter: (id) => idbPersister(id),
  pull: async ({ name, lastFinishedSyncEnd }) => {
    // lastFinishedSyncEnd is always undefined on the first sync
    const response = await fetch(`/api/collections/${collectionOptions.name}?since=${lastFinishedSyncStart}`)
    return await response.json()
  },
  // ...
})
 
const collection = new Collection()
syncManager.addCollection(collection, {
  name: 'todos',
})
 
syncManager.sync('todos') // will always load all the data instead of just data since `lastFinishedSyncEnd`
```

My [current workaround](https://github.com/obedm503/trellix-offline/blob/12a41ba6fe7c49b9c2b5a732a07c469c2c5de744/signaldb/src/collections.tsx#L139-L166) is to delay calling `sync` or `syncAll` until `syncManager.syncOperations`, `syncManager.changes`, `syncManager.remoteChanges`, and `syncManager.snapshots` have all emitted the `persistence.pullCompleted` event once. This is not ideal because I'm using private properties. Ideally, the sync manager would emit some type of `ready` or `init` event once its internal collections have all loaded into memory.

### PR DESCRIPTION
**Pull request by maxnowack**
resolves #943

### CODE REVIEW

File: packages/signaldb/src/SyncManager/index.ts [hunk 1]
```diff
@@ -235,6 +273,14 @@ export default class SyncManager<
     }, { fields: { status: 1 } }) != null
   }
 
+  /**
+   * Checks if the sync manager is ready to sync.
+   * @returns A promise that resolves when the sync manager is ready to sync.
+   */
+  public async isReady() {
+    await this.persistenceReady
```
Comment (Cmacu) [inline packages/signaldb/src/SyncManager/index.ts:281]: Doesn't this hold an array of responses? I guess the idea is that the check is that the array is not empty, but it's a bit confusing without explicit conversion to boolean

File: packages/signaldb/src/SyncManager/applyChanges.ts [hunk 2]
```diff
@@ -16,9 +17,19 @@ export default function applyChanges<ItemType extends BaseItem<IdType>, IdType>(
...
+      if (itemExists) {
+        collection.updateOne({ id: change.data.id } as Record<string, any>, { $set: change.data })
+      } else {
+        collection.insert(change.data)
+      }
     } else if (change.type === 'update') {
-      collection.updateOne({ id: change.data.id } as Record<string, any>, change.data.modifier)
+      const itemExists = collection.findOne({ id: change.data.id } as Record<string, any>)
+      if (itemExists) {
+        collection.updateOne({ id: change.data.id } as Record<string, any>, change.data.modifier)
```
Comment (Cmacu) [inline packages/signaldb/src/SyncManager/applyChanges.ts:29]: it took me a moment to realize that the difference between the insert and the update is the `data.modifier` vs `data`. I am also curious about the cast to `Record<string, any>` given that the `collection` and `changes` should be based on the same Generic type provided during the collection creation.

File: packages/signaldb/src/SyncManager/index.ts (hunk 1 above)
Comment (obedm503) [reply packages/signaldb/src/SyncManager/index.ts:281]: All the promises are awaited together with `Promise.all` so it's not an array of promises. `isReady()` is more of a [semaphore](https://en.wikipedia.org//wiki/Semaphore_(programming)), and not something to check and ignore. It's meant to always hold execution.

File: packages/signaldb/src/SyncManager/applyChanges.ts (hunk 2 above)
Comment (maxnowack) [reply packages/signaldb/src/SyncManager/applyChanges.ts:29]: I’m also not really happy with this code. It was a bit late yesterday 😀
The only reason for the cast to `Record<string, any>` is to please the TypeScript Compiler

File: packages/signaldb/src/SyncManager/index.ts (hunk 1 above)
Comment (maxnowack) [reply packages/signaldb/src/SyncManager/index.ts:281]: Exactly. The `Promise.all` waits for all promises together and resolves when all promises are fulfilled. If `this.persistenceReady` is awaited later on, it will resolve immediately as it is already a resolved promise.

File: packages/signaldb/src/SyncManager/applyChanges.ts (hunk 2 above)
Comment (maxnowack) [reply packages/signaldb/src/SyncManager/applyChanges.ts]: I refactored this code to make it more readable

File: packages/signaldb/src/SyncManager/index.ts (hunk 1 above)
Comment (Cmacu) [reply packages/signaldb/src/SyncManager/index.ts:281]: I learned something new today! Thanks for explaining this @obedm503!
